#
# PLUGINS OPTIONS
#
portname                  0
autofire                  0
layout                    1
discord                   0
hiscore                   0
gdbstub                   0
cheatfind                 0
data                      1
timer                     0
dummy                     0
console                   0
cheat                     0
timecode                  0
inputmacro                0
